/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class module_video_jnc_myffmpeg_SDLActivity_ShowTextInputTask */

#ifndef _Included_module_video_jnc_myffmpeg_SDLActivity_ShowTextInputTask
#define _Included_module_video_jnc_myffmpeg_SDLActivity_ShowTextInputTask
#ifdef __cplusplus
extern "C" {
#endif
#undef module_video_jnc_myffmpeg_SDLActivity_ShowTextInputTask_HEIGHT_PADDING
#define module_video_jnc_myffmpeg_SDLActivity_ShowTextInputTask_HEIGHT_PADDING 15L
#ifdef __cplusplus
}
#endif
#endif
