/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class module_video_jnc_myffmpeg_SDLActivity */

#ifndef _Included_module_video_jnc_myffmpeg_SDLActivity
#define _Included_module_video_jnc_myffmpeg_SDLActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef module_video_jnc_myffmpeg_SDLActivity_COMMAND_CHANGE_TITLE
#define module_video_jnc_myffmpeg_SDLActivity_COMMAND_CHANGE_TITLE 1L
#undef module_video_jnc_myffmpeg_SDLActivity_COMMAND_UNUSED
#define module_video_jnc_myffmpeg_SDLActivity_COMMAND_UNUSED 2L
#undef module_video_jnc_myffmpeg_SDLActivity_COMMAND_TEXTEDIT_HIDE
#define module_video_jnc_myffmpeg_SDLActivity_COMMAND_TEXTEDIT_HIDE 3L
#undef module_video_jnc_myffmpeg_SDLActivity_COMMAND_USER
#define module_video_jnc_myffmpeg_SDLActivity_COMMAND_USER 32768L
/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    nativeLowMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_nativeLowMemory
  (JNIEnv *, jclass);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    nativeQuit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_nativeQuit
  (JNIEnv *, jclass);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    nativePause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_nativePause
  (JNIEnv *, jclass);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    nativeResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_nativeResume
  (JNIEnv *, jclass);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    onNativeResize
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_onNativeResize
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    onNativePadDown
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_onNativePadDown
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    onNativePadUp
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_onNativePadUp
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    onNativeJoy
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_onNativeJoy
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    onNativeHat
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_onNativeHat
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    onNativeKeyDown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_onNativeKeyDown
  (JNIEnv *, jclass, jint);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    onNativeKeyUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_onNativeKeyUp
  (JNIEnv *, jclass, jint);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    onNativeKeyboardFocusLost
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_onNativeKeyboardFocusLost
  (JNIEnv *, jclass);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    onNativeTouch
 * Signature: (IIIFFF)V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_onNativeTouch
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    onNativeAccel
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_onNativeAccel
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    onNativeSurfaceChanged
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_onNativeSurfaceChanged
  (JNIEnv *, jclass);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    onNativeSurfaceDestroyed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_onNativeSurfaceDestroyed
  (JNIEnv *, jclass);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    nativeFlipBuffers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_nativeFlipBuffers
  (JNIEnv *, jclass);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    nativeAddJoystick
 * Signature: (ILjava/lang/String;IIIII)I
 */
JNIEXPORT jint JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_nativeAddJoystick
  (JNIEnv *, jclass, jint, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     module_video_jnc_myffmpeg_SDLActivity
 * Method:    nativeRemoveJoystick
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_module_video_jnc_myffmpeg_SDLActivity_nativeRemoveJoystick
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
