/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class module_video_jnc_myffmpeg_FFmpegUtils */

#ifndef _Included_module_video_jnc_myffmpeg_FFmpegUtils
#define _Included_module_video_jnc_myffmpeg_FFmpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     module_video_jnc_myffmpeg_FFmpegUtils
 * Method:    stringNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_module_video_jnc_myffmpeg_FFmpegUtils_stringNative
  (JNIEnv *, jclass);

/*
 * Class:     module_video_jnc_myffmpeg_FFmpegUtils
 * Method:    stringJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_module_video_jnc_myffmpeg_FFmpegUtils_stringJni
  (JNIEnv *, jclass);

/*
 * Class:     module_video_jnc_myffmpeg_FFmpegUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_module_video_jnc_myffmpeg_FFmpegUtils_decode
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     module_video_jnc_myffmpeg_FFmpegUtils
 * Method:    stream
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_module_video_jnc_myffmpeg_FFmpegUtils_stream
  (JNIEnv *, jclass, jstring, jstring);


/*
 * Class:     module_video_jnc_myffmpeg_FFmpegUtils
 * Method:    encode
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_module_video_jnc_myffmpeg_FFmpegUtils_encode
        (JNIEnv *, jclass, jstring ,jstring);





JNIEXPORT jint JNICALL Java_module_video_jnc_myffmpeg_FFmpegUtils_transcodeing
        (JNIEnv *env, jclass clazz, jstring inputStr, jstring outputStr);


JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_FFmpegUtils_myInit(JNIEnv *, jclass ,jstring outputVStr);
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_FFmpegUtils_closeMyFFmpeg(JNIEnv * , jclass  );
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_FFmpegUtils_encodeCamera(JNIEnv *env, jclass clazz);
#ifdef __cplusplus
}
#endif
#endif
