/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class module_video_jnc_myffmpeg_SDLActivity_SDLCommandHandler */

#ifndef _Included_module_video_jnc_myffmpeg_SDLActivity_SDLCommandHandler
#define _Included_module_video_jnc_myffmpeg_SDLActivity_SDLCommandHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
