/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class module_video_jnc_myffmpeg_SDLUtils */

#ifndef _Included_module_video_jnc_myffmpeg_SDLUtils
#define _Included_module_video_jnc_myffmpeg_SDLUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     module_video_jnc_myffmpeg_SDLUtils
 * Method:    initSDLTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_module_video_jnc_myffmpeg_SDLUtils_initSDLTest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
